### ISSUE TITLE
Add LANG to every package

### ISSUE THREAD

**Issue by seppeljordan** [garbas/nixpkgs-python#10]
In the file overrides.nix there is a comment that reads `add this to every package`.  Here is a link:
https://github.com/garbas/nixpkgs-python/blob/master/overrides.nix#L63

This is probably referring to `LANG="en_US.UTF-8` in the package nix expression.  DO we want to add this to every package?  And if so, what is the reasoning behind this?

(edit: grammar)

**Comment by garbas** [comment]
Reason for this is that reading any non ASCII README.rst would result in an error since by default LANG=C is used.

**Comment by seppeljordan** [comment]
#14 solved this
