### ISSUE TITLE
travis builds sometimes fail

### ISSUE THREAD

**Issue by seppeljordan** [garbas/nixpkgs-python#21]
Sometimes rsync asks for user input when trying to copy python wheels to the wheel cache.
@garbas Should we force a yes there?

```
$ rsync -avh --ignore-existing /tmp/pypi2nix/cache/wheel/*.whl travis@garbas.si:/var/travis/wheels_cache/
The authenticity of host 'garbas.si (81.4.127.29)' can't be established.
ED25519 key fingerprint is 42:c5:6e:0f:5f:8c:73:0e:ce:01:43:f5:e7:bc:4f:a8.
Are you sure you want to continue connecting (yes/no)? 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by garbas** [comment]
@seppeljordan maybe, i'm not 100% sure why this fails in the first place. since `garbas.si` host is added in `.travis.yml`

**Comment by seppeljordan** [comment]
@garbas We have now a similar problem over at `pypi2nix`.  I don't know enough about travis yet to fully understand the issue.  I'll try to figure something out.

**Comment by garbas** [comment]
maybe just adding `StrictHostKeyChecking=no` option for `garbas.si` host would make things less secure, but more robust

**Comment by garbas** [comment]
this is the documentation i was following when writing this line 

https://docs.travis-ci.com/user/ssh-known-hosts/

**Comment by garbas** [comment]
actually maybe i can just add the ssh public key for garbas.si host

**Comment by garbas** [comment]
I'm trying this on pypi2nix and if it works i'm going to do this also on `nixpkgs-python`

**Comment by garbas** [comment]
i added ssh pubkey in travis.yml for garbas.si for both pypi2nix and nixpkgs-python repo. i think we are good to close this issue

**Comment by garbas** [comment]
look like this doesn't fix the issue
https://travis-ci.org/garbas/pypi2nix/builds/347219672 

:(

**Comment by garbas** [comment]
i guess something changed with openssl. now it required password to decrypt `deploy_rsa.enc`.
i think something is going wrong with travis and maybe we just need to "wait"

**Comment by garbas** [comment]
fixed in pypi2nix now

**Comment by garbas** [comment]
and it looks also that nixpkgs-python was fixed, closing...
